// Thermal page driver | Spencer Tipping
// Licensed under the terms of the MIT source code license

$(montenegro.clone('std')(function () {
  '#create-story' >jqc> $('#story').clone().appendTo('#stories');
}));

// Generated by SDoc 
