// Thermal server | Spencer Tipping
// Licensed under the terms of the MIT source code license

caterwaul.clone('std db.file montenegro')(function () {
  let[db = caterwaul.db.file('db')] in
  caterwaul.montenegro.server(8080) /se[
    _.rpc('/stories', 'Invoke this with no arguments to get the ID of each defined story (as an array)', fn_[db.index('all', this)]).
      rpc('/story',   '(name, optional story) -> story. Reads or writes story data.', fn[name, story][story ? db(name)(story)('all')(this) : db(name)(this)]),

   _.alias('/', '/index.html'),
   _.file('', 'client')]})();

// Generated by SDoc 
