// Thermal server | Spencer Tipping
// Licensed under the terms of the MIT source code license

caterwaul.clone('std db.file montenegro')(function () {
  let[db = caterwaul.db.file('db')] in
  caterwaul.montenegro.server(8080) /se[_.file('/client', 'client'),
                                        _.rpc('/stories', 'Invoke this with no arguments to get the ID of each defined story (as an array)', fn_[db.index('all', this)]),
                                        _.rpc('/story',   '(name, story?) -> story. Reads or writes story data.', fn[name, story][story ? db(name)(story)(this) : db(name)(this)])]})();

// Generated by SDoc 
